cms/urls.py
from django.urls import path
from cms.populate import populate
from cms.views import PostListView, DraftListView, publish_post_view, PostCreateView, PostUpdateView, \
    save_post_to_user_view, \
    SavedPostListView, assign_post_view, add_review_view, delete_review_view, PostDetailView, SubscriptionListView, \
    update_subscriptions, assign_editor_view, PostDeleteView, CategoryCreateView, content_status_view

urlpatterns = [
    path('', PostListView.as_view(), name="post_list"),
    path('drafts', DraftListView.as_view(), name="draft_list"),
    path('new', PostCreateView.as_view(), name="post_form"),
    path('saved', SavedPostListView.as_view(), name="saved_posts"),
    path('subscriptions', SubscriptionListView.as_view(), name="subscriptions"),
    path('subscriptions/<int:pk>/update', update_subscriptions, name='update_subscription'),

    path('<int:pk>/publish', publish_post_view, name="publish_post"),
    path('<int:pk>/edit', PostUpdateView.as_view(), name="post_update"),
    path('<int:pk>/save', save_post_to_user_view, name='save_post'),
    path('<int:pk>/assign', assign_post_view, name="assign_post"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete_post"),
    path('<int:pk>/status', content_status_view, name="content_status"),
    path('<int:pk>/add_review', add_review_view, name="add_review"),
    path('<int:pk>/delete_review', delete_review_view, name="delete_review"),
    path('add_category', CategoryCreateView.as_view(), name="create_category"),
    path('<int:pk>/assign_editor', assign_editor_view, name="assign_editor"),
    path('<int:pk>', PostDetailView.as_view(), name="post_detail"),

    path('populate', populate, name="populate"),
]

website/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from website.views import login_view, registration_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('login_form', login_view, name="login_form"),
    path('registration', registration_view, name='registration_form'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(
        blank=False,
        unique=True,
        max_length=50,
    )

    def __str__(self):
        return self.name


class Post(models.Model):

    authors = models.ManyToManyField(
        User,
        related_name='authored_posts',
        blank=True,
    )
    title = models.CharField(
        blank=False,
        max_length=100,
    )
    content = models.TextField(
        blank=False,
    )
    published = models.BooleanField(
        default=False,
    )
    categories = models.ManyToManyField(
        Category,
        related_name='posts',
        blank=True
    )
    saved_by_users = models.ManyToManyField(
        User,
        related_name='saved_posts',
        blank=True,
    )
    assigned_users = models.ManyToManyField(
        User,
        related_name='assigned_posts',
        blank=True,
    )
    image = models.ImageField(
        blank=True,
        upload_to='images'
    )
    complete = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']
        permissions = (("publish_post", "Publish post"), ("assign_editors", "Assign editors"))


class Review(models.Model):

    content = models.TextField(
        blank=False,
    )
    editor = models.ForeignKey(
        User,
        related_name="post_reviews",
        blank=False,
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        related_name="reviews",
        on_delete=models.CASCADE,
    )


class Subscription(models.Model):
    owner = models.OneToOneField(
        User,
        blank=True,
        on_delete=models.CASCADE,
        related_name='subscription'
    )
    authors = models.ManyToManyField(
        User,
        blank=True,
        related_name='subscriber_objects'
    )
    categories = models.ManyToManyField(
        Category,
        blank=True,
        related_name='subscriptions'
    )

website/forms.py
from django.contrib.auth.models import User
from django import forms


class RegistrationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }
        help_texts = {
            'username': None,
        }

website/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from website.forms import RegistrationForm


def login_view(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            logout(request)
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
            elif User.objects.filter(username=username).exists():
                messages.add_message(request, messages.ERROR, 'Incorrect password')
            else:
                messages.add_message(request, messages.ERROR, 'Username does not exist')
        return HttpResponseRedirect(reverse('post_list'))


def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if not User.objects.filter(username=request.POST['username']).exists():
            user = form.save()
            user.set_password(request.POST['password'])
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('post_list'))
        else:
            messages.add_message(request, messages.ERROR, 'Username is already taken')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', None))
    else:
        form = RegistrationForm()
        return render(request, 'registration/registration_form.html', {'form': form})

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'website/semantic/dist/semantic.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}">
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src="{% static 'website/semantic/dist/semantic.min.js' %}"></script>

    {% block head %} {% endblock %}
</head>

<body>
    {% block header %} {% include 'website/header.html' %} {% endblock header %}
    {% block body %}
    {% endblock %}
</body>
</html>

website/templates/website/header.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'website/css/menu.css' %}">

<div class="ui inverted vertical masthead center aligned segment">
    <div class="ui text container">
        <h1 class="ui inverted header">
            Life on a Branch
        </h1>
        <h2>Generic subheader</h2>
    </div>

</div>

{% with url_name=request.resolver_match.url_name %}
<div class="ui borderless main menu sticky" inverted>
    <div class="ui text container">
        <a href="{% url 'post_list' %}" class="{% if url_name == 'post_list' %}active{% endif %} item">Home</a>

        {% if perms.cms.change_post %}
            <a href=" {% url 'draft_list' %}" class="{% if url_name == 'draft_list' %}active{% endif %} item">
                Drafts
            </a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'saved_posts' %}" class="{% if url_name == 'saved_posts' %}active{% endif %} item">Saved</a>
        {% endif %}

        {% if perms.cms.add_post %}
            <a href="{% url 'post_form' %}" class="{% if url_name == 'post_form' %}active{% endif %} item">New</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'subscriptions' %}" class="{% if url_name == 'subscriptions' %}active{% endif %} item">Subscriptions</a>
        {% endif %}

        {% if perms.cms.add_category %}
            <a href="{% url 'create_category' %}" class="{% if url_name == 'create_category' %}active{% endif %} item">Add Category</a>
        {% endif %}

        {% if user.is_superuser %}
            <a href="/admin" class="item">
                Admin
            </a>
        {% endif %}

        <div class="ui right floated item">
            {% include "registration/login_form.html" %}
        </div>

    </div>
</div>
{% endwith %}

<script>
    $(document)
        .ready(function() {
            // fix main menu to page on passing
            $('.main.menu').visibility({
                type: 'fixed'
            });
            $('.overlay').visibility({
                type: 'fixed',
                offset: 80
            });
            // show dropdown on hover
            $('.main.menu  .ui.dropdown').dropdown({
                on: 'hover'
            });
        });

    /* $('.ui.main.menu > .ui.text.container').css( "border", "3px double red" ); */
</script>