cms/urls.py
from django.urls import path
from cms.populate import populate
from cms.views import PostListView, DraftListView, publish_post_view, PostCreateView, PostUpdateView, \
    save_post_to_user_view, \
    SavedPostListView, assign_post_view, add_review_view, delete_review_view, PostDetailView, SubscriptionListView, \
    update_subscriptions, assign_editor_view, PostDeleteView, CategoryCreateView, content_status_view

urlpatterns = [
    path('', PostListView.as_view(), name="post_list"),
    path('drafts', DraftListView.as_view(), name="draft_list"),
    path('new', PostCreateView.as_view(), name="post_form"),
    path('saved', SavedPostListView.as_view(), name="saved_posts"),
    path('subscriptions', SubscriptionListView.as_view(), name="subscriptions"),
    path('subscriptions/<int:pk>/update', update_subscriptions, name='update_subscription'),

    path('<int:pk>/publish', publish_post_view, name="publish_post"),
    path('<int:pk>/edit', PostUpdateView.as_view(), name="post_update"),
    path('<int:pk>/save', save_post_to_user_view, name='save_post'),
    path('<int:pk>/assign', assign_post_view, name="assign_post"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete_post"),
    path('<int:pk>/status', content_status_view, name="content_status"),
    path('<int:pk>/add_review', add_review_view, name="add_review"),
    path('<int:pk>/delete_review', delete_review_view, name="delete_review"),
    path('add_category', CategoryCreateView.as_view(), name="create_category"),
    path('<int:pk>/assign_editor', assign_editor_view, name="assign_editor"),
    path('<int:pk>', PostDetailView.as_view(), name="post_detail"),

    path('populate', populate, name="populate"),
]

website/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from website.views import login_view, registration_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('login_form', login_view, name="login_form"),
    path('registration', registration_view, name='registration_form'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(
        blank=False,
        unique=True,
        max_length=50,
    )

    def __str__(self):
        return self.name


class Post(models.Model):

    authors = models.ManyToManyField(
        User,
        related_name='authored_posts',
        blank=True,
    )
    title = models.CharField(
        blank=False,
        max_length=100,
    )
    content = models.TextField(
        blank=False,
    )
    published = models.BooleanField(
        default=False,
    )
    categories = models.ManyToManyField(
        Category,
        related_name='posts',
        blank=True
    )
    saved_by_users = models.ManyToManyField(
        User,
        related_name='saved_posts',
        blank=True,
    )
    assigned_users = models.ManyToManyField(
        User,
        related_name='assigned_posts',
        blank=True,
    )
    image = models.ImageField(
        blank=True,
        upload_to='images'
    )
    complete = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']
        permissions = (("publish_post", "Publish post"), ("assign_editors", "Assign editors"))


class Review(models.Model):

    content = models.TextField(
        blank=False,
    )
    editor = models.ForeignKey(
        User,
        related_name="post_reviews",
        blank=False,
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        related_name="reviews",
        on_delete=models.CASCADE,
    )


class Subscription(models.Model):
    owner = models.OneToOneField(
        User,
        blank=True,
        on_delete=models.CASCADE,
        related_name='subscription'
    )
    authors = models.ManyToManyField(
        User,
        blank=True,
        related_name='subscriber_objects'
    )
    categories = models.ManyToManyField(
        Category,
        blank=True,
        related_name='subscriptions'
    )

cms/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Review, Subscription


class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['categories'].form = forms.MultipleChoiceField()
        self.fields['categories'].widget.attrs['class'] = 'ui multiple search selection dropdown'

        author_qs = User.objects.filter(groups__name='authors').exclude(username=self.user.username)

        self.fields['authors'].form = forms.ModelMultipleChoiceField(queryset=author_qs)
        self.fields['authors'].queryset = author_qs
        self.fields['authors'].widget.attrs['class'] = 'ui multiple search selection dropdown'

    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'categories', 'authors', ]


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['content']
        labels = {'content': 'Review'}


class SubscriptionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categories'].form = forms.MultipleChoiceField()
        self.fields['categories'].widget.attrs['class'] = 'ui multiple search selection dropdown'

        self.fields['authors'].form = forms.ModelMultipleChoiceField(queryset=None)
        self.fields['authors'].queryset = User.objects.filter(groups__name='authors')
        self.fields['authors'].widget.attrs['class'] = 'ui multiple search selection dropdown'

    class Meta:
        model = Subscription
        fields = ['authors', 'categories', ]


class AssignForm(forms.Form):

    editors = forms.ModelMultipleChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['editors'].queryset = User.objects.filter(groups__name='editor')
        self.fields['editors'].widget.attrs['class'] = 'ui multiple search selection dropdown'

cms/views.py
from itertools import chain
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from cms.forms import PostForm, ReviewForm, SubscriptionForm, AssignForm
from cms.models import Post, Category, Review, Subscription
from cms.templatetags.auth_extras import has_group


class PostListView(ListView):
    context_object_name = 'posts'
    queryset = Post.objects.filter(published=True)

    def get_context_data(self, *, object_list=queryset, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class DraftListView(PermissionRequiredMixin, PostListView):
    queryset = Post.objects.filter(published=False)
    template_name = 'cms/post_list.html'
    permission_required = 'cms.change_post'


class SavedPostListView(PostListView):
    context_object_name = 'posts'
    template_name = 'cms/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(saved_by_users__username=self.request.user.username)


class PostCreateView(PermissionRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = '/drafts'
    permission_required = 'cms.add_post'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        post.authors.set(form.cleaned_data['authors'])
        post.categories.set(form.cleaned_data['categories'])
        post.authors.add(self.request.user)
        post.save()
        return HttpResponseRedirect(reverse('post_detail', kwargs={'pk': post.pk}))


class CategoryCreateView(PermissionRequiredMixin, CreateView):
    model = Category
    fields = ('name',)
    success_url = '/add_category'
    permission_required = 'cms.add_category'
    template_name = "cms/category_create.html"


class PostDeleteView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user in self.get_object().authors.all()


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostCreateView.form_class

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        post = form.save(commit=False)
        if 'author' in self.request.user.groups.all():
            post.authors.add(self.request.user)
        post.authors.set(form.cleaned_data['authors'])
        post.categories.set(form.cleaned_data['categories'])
        post.save()
        return HttpResponseRedirect(reverse('post_detail', kwargs={'pk': post.pk}))

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        user = self.request.user
        return user.is_superuser or user in chain(post.authors.all(), post.assigned_users.all())


class PostDetailView(UserPassesTestMixin, DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['review_form'] = ReviewForm
        context['assign_form'] = AssignForm
        return context

    def test_func(self):
        post = self.get_object()
        return post.published or self.request.user.has_perm('cms.change_post')


class SubscriptionListView(LoginRequiredMixin, PostListView):
    template_name = 'cms/subscriptions.html'

    def dispatch(self, request, *args, **kwargs):
        try:
            request.user.subscription
        except AttributeError:
            if request.user.is_authenticated:
                request.user.subscription = Subscription.objects.create(owner=request.user)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        sub = self.request.user.subscription
        by_category = Post.objects.filter(categories__in=sub.categories.all()).exclude(published=False)
        by_author = Post.objects.filter(authors__in=sub.authors.all()).exclude(published=False)
        return sorted(chain(by_category, by_author), key=(lambda p: p.id))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SubscriptionForm()
        context['subscription_page'] = True
        return context


########################################################
########################################################


def publish_post_view(request, pk):
    if request.method == 'POST':
        if request.user.has_perm('cms.publish_post'):
            post = Post.objects.get(pk=pk)
            if post.published:
                post.published = False
                post.save()
                return HttpResponseRedirect(reverse('draft_list'))
            else:
                post.published = True
                post.save()
            return HttpResponseRedirect(reverse('post_list'))
        raise PermissionDenied("only editors can publish posts")


def save_post_to_user_view(request, pk):
    if request.method == 'POST':
        if request.user.is_authenticated:
            post = Post.objects.get(pk=pk)
            if post.saved_by_users.filter(username=request.user.username).exists():
                post.saved_by_users.remove(request.user)
            else:
                post.saved_by_users.add(request.user)
            post.save()
            return HttpResponseRedirect(reverse('post_detail', kwargs={'pk': post.pk}))
        raise PermissionDenied("Only logged in users can save posts")


def assign_post_view(request, pk):
    if request.method == 'POST':
        if request.user.has_perm("cms.add_review"):
            post = Post.objects.get(pk=pk)
            if post.assigned_users.filter(pk=request.user.pk).exists():
                post.assigned_users.remove(request.user)
            else:
                post.assigned_users.add(request.user)
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', None))
        raise PermissionDenied("Only editors can review posts")


def add_review_view(request, pk):
    if request.user.has_perm("cms.add_review"):
        post = Post.objects.get(pk=pk)
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.post = post
                review.editor = request.user
                review.save()
                post.reviews.add(review)
                post.save()
                return HttpResponseRedirect(reverse('post_detail', kwargs={'pk': post.pk}))
    raise PermissionDenied("Only editors can review posts")


def delete_review_view(request, pk):
    if request.method == 'POST':
        if request.user == Review.objects.get(pk=pk).editor or request.user.has_perm("cms.delete_review"):
            Review.objects.filter(pk=pk).delete()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', None))
        raise PermissionDenied("Only admins can delete the reviews of other users")


def update_subscriptions(request, pk):
    if request.user.is_authenticated and request.method == 'POST':
        subscription = get_object_or_404(Subscription, pk=pk)
        form = SubscriptionForm(request.POST)
        if not request.user == subscription.owner:
            raise PermissionDenied("You cannot set other people's permissions")
        if form.is_valid():
            subscription.authors.set(form.cleaned_data['authors'])
            subscription.categories.set(form.cleaned_data['categories'])
            return HttpResponseRedirect(reverse_lazy('subscriptions'))
    raise PermissionDenied("Permission missing")


def assign_editor_view(request, pk):
    if request.method == 'POST':
        if not request.user.has_perm('cms.assign_editors'):
            raise PermissionDenied("Only editors can edit posts")
        editor_ids = [request.POST['editors']]
        post = Post.objects.get(pk=pk)
        for editor_id in editor_ids:
            editor = User.objects.get(pk=editor_id)
            post.assigned_users.add(editor)
        return HttpResponseRedirect('/{}'.format(pk))


def content_status_view(request, pk):
    if request.method == 'POST':
        if request.user.has_perm("cms.change_post"):
            post = Post.objects.get(pk=pk)
            if post.complete:
                post.complete = False
            else:
                post.complete = True
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', None))
    raise PermissionDenied("Only editors can mark content as complete")

cms/templates/cms/assign_authors_modal.html
{% load static %}
<div class="ui modal">
    <div class="ui text container">
        <form class="ui form" method="POST" action="{% url 'assign_editor' pk=post.pk %}"  enctype="multipart/form-data">
            {% csrf_token %}
            {{ assign_form.as_p }}
            <button type="submit" class="ui primary button">Save</button>
            <button type="reset" onclick="hide_modal()" class="ui button">Cancel</button>
        </form>
    </div>
    <p><br></p>
</div>

cms/templates/cms/assign_buttons.html
{% if request.user in post.assigned_users.all %}
    <form method="post" action="{% url "assign_post" pk=post.pk %}">
        {% csrf_token %}
        <button type="submit" class="ui red button">Quit review</button>
    </form>
{% else %}
    <form method="post" action="{% url "assign_post" pk=post.pk %}">
        {% csrf_token %}
        <button type="submit" class="ui green button">Review</button>
    </form>
{% endif %}

cms/templates/cms/assigned_editors.html
{% if post.assigned_users.all %}
    <p>Being reviewed by:
        {{ post.assigned_users.all|join:", " }}
    </p>
{% endif %}

cms/templates/cms/authors_list.html
<p id="post-author-list">
    Authors:
    {% for author in authors %}
        <button class="ui tiny white button">{{ author }}</button>
    {% empty %}
        <em>None</em>
    {% endfor %}
</p>

cms/templates/cms/category_create.html
{% extends 'website/base.html' %}
{% block body %}
<div class="ui text container">
    <div class="ui form">

        <form method="post" action="{% url "create_category" %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="ui green button" value="Submit"/>
        </form>

   </div>
</div>

{% endblock %}

cms/templates/cms/content_status.html
<p id="post-mark-content">
    Status:
    {% if post.complete %}
        complete
    {% else %}
        incomplete
    {% endif %}
</p>

cms/templates/cms/post_confirm_delete.html
{% extends 'website/base.html' %}

{% block body %}
<div class="ui text container">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="ui button">
    </form>
</div>
{% endblock %}

cms/templates/cms/post_detail.html
{% extends 'website/base.html'%}
{% load static %}
{% load auth_extras %}

{% block body %}
<div class="ui text container">

    {% if not post.published %}
        {% include "cms/assigned_editors.html" %}
    {% endif %}

    {% if not post.published %}
        {% include "cms/content_status.html" %}
    {% endif %}

    <h1>{{ post.title }}</h1>
    {% if post.image %}
        <img src = '{{ post.image.url }}' width = "100%">
    {% endif %}

    {% with post.categories.all as categories %}
        {% include "cms/category_list.html" %}
    {% endwith %}
    {% with post.authors.all as authors %}
        {% include "cms/authors_list.html" %}
    {% endwith %}

    <p>{{ post.content }}</p>

    {% if user.is_authenticated %}
        <div class="ui relaxed grid">
            {% if request.user in post.assigned_users.all or request.user in post.authors.all  %}
                <div class="two wide column">
                    <a href="{% url "post_update" pk=post.pk %}" class="ui blue button">Edit</a>
                </div>
            {% endif %}

            <div class="two wide column">
                <form method="post" action="{% url "save_post" pk=post.pk %}">
                    {% csrf_token %}
                    {% if user in post.saved_by_users.all %}
                        <button type="submit" class="ui red button">Unsave</button>
                    {% else %}
                        <button type="submit" class="ui green button">Save</button>
                    {% endif %}
                </form>
            </div>

            {% if not post.published and perms.cms.publish_post %}
                <div class="two wide column">
                    <button type="button" onclick="show_modal()" class="ui tiny blue button">Assign editors</button>
                </div>
                <div class="two wide column">
                    <form method="post" action="{% url "publish_post" pk=post.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="ui blue button">Publish</button>
                    </form>
                </div>
            {% endif %}


            {%  if post.published and perms.cms.publish_post %}
                <div class = "two wide column">
                    <form method="post" action = "{% url "publish_post" pk=post.pk %}">
                        {% csrf_token %}
                        <button type = "submit" class="ui red button">Unpublish</button>
                    </form>
                </div>
            {% endif %}

            {% if request.user in post.authors.all and not post.published%}
                <div class = "two wide column">
                    <a href="{% url "delete_post" pk=post.pk %}" class="ui red button">Delete</a>
                </div>
            {% endif %}

            {% if not post.published and perms.cms.add_review %}
                <div class="two wide column">
                    {% include "cms/assign_buttons.html" %}
                </div>

                <div class="two wide column">
                    {% include "cms/status_buttons.html" %}
                </div>
            {% endif %}
        </div>

        {% endif %}
        {% if not post.published %}
            {% if request.user in post.assigned_users.all or perms.cms.publish_post%}
                {% include "cms/review_form.html" %}
                {% include "cms/review_detail.html" %}
            {% endif %}
        </div>
        {% endif %}
    <p><br></p>
</div>

{% if perms.cms.assign_editors %}
{% include "cms/assign_authors_modal.html" %}
{% endif %}

<script type="text/javascript" src="{% static 'cms/javascript/sort_by_category.js' %}"></script>
<script>
 function show_modal() {
     $('.ui.modal').modal('show');
 }
 function hide_modal() {
     $('.ui.modal').modal('hide');
 }
 $('.ui.dropdown').dropdown();
</script>

{% endblock %}

cms/templates/cms/post_form.html
{% extends 'website/base.html' %}

{% block body %}
<div class="ui text container">

    <h1>Post</h1>

    <form method="post" class="ui form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="ui blue button">
    </form>

</div>
<script>
        $('.ui.dropdown').dropdown();
</script>
{% endblock %}

cms/templates/cms/post_list.html
{% extends 'website/base.html' %}
{% load staticfiles %}
{% load auth_extras %}

{% block body %}

    <h1>Posts</h1>

    {% for post in posts %}

        <h3><a href="{% url "post_detail" pk=post.pk %}">
            {{ post.title }}
        </a></h3>
        <p>{{ post.content }}</p>

        {% if not post.published and request.user|has_group:"editor" %}
        <form method="post" action="{% url "publish_post" pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class="button">Publish</button>
        </form>
        {% endif %}

    {% endfor %}

{% endblock %}

cms/templates/cms/review_form.html
{% load static %}
<div class="ui form">
    <button onclick="show_form()" id="show-review-form-button" class="ui white button">Add review</button>
    <div class="field" id="review-form">
        <form method="post" action="{% url "add_review" pk=post.pk %}" >
            {% csrf_token %}
            {{ review_form }}
            <button type="submit" class="ui green button">Submit</button>
        </form>
    </div>
</div>
<script type="text/javascript" src="{% static 'cms/javascript/hide_review_form.js' %}"></script>

cms/templates/cms/status_buttons.html
{% if perms.cms.change_post %}
    {% if not post.complete %}
        <form method="post" action="{% url "content_status" pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class="ui green button">Complete</button>
        </form>
    {% else %}
        <form method="post" action="{% url "content_status" pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class="ui red button">Incomplete</button>
        </form>
    {% endif %}
{% endif %}

cms/templates/cms/subscriptions.html
{% extends 'website/base.html' %}
{% load static %}
{% load auth_extras %}

{% block head %}
{% endblock %}

{% block body %}

<div class="ui text container">
    <h1>Subscriptions</h1>

    <h3>You subscribe to:</h3>
    <div class="ui equal width grid">
        <div class="column">
            {% with user.subscription.authors.all as authors %}
                {% include 'cms/authors_list.html' %}
            {% endwith %}
        </div>

        <div class="left aligned column">
        {% with user.subscription.categories.all as categories %}
            {% include 'cms/category_list.html' %}
        {% endwith %}
        </div>
    </div>

    <div class="ui grid">
        <div class="two wide column">
            <h3>Filter:</h3>
        </div>
        <div class="eight wide column">
            <select onchange="filterPosts()" id="dropdown" multiple="" class="ui fluid search dropdown">
                {% for category in categories %}
                  <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="four wide column">
            <button type="button" onclick="show_modal()" class="ui tiny blue button">Manage subscriptions</button>
        </div>
    </div>
    <p></p>
    <div id="post_list">
    {% for post in posts %}
        <div  id="{{ post.pk }}" class="post-container">
            <h2>
                <a href="{% url "post_detail" pk=post.pk %}">
                    {{ post.title }}
                </a>
            </h2>
            <p>{{ post.content|truncatechars:140 }}</p>
            {% with post.categories.all as categories %}
                {% include "cms/category_list.html" %}
            {% endwith %}
            {% with post.authors.all as authors %}
                {% include "cms/authors_list.html" %}
            {% endwith %}
            {% if not post.published %}

                {% include "cms/assigned_editors.html" %}

                {% if request.user|has_group:"editor" %}
                    {% include "cms/assign_buttons.html" %}
                {% endif %}

            {% endif %}
        <p></p>
        </div>
    {% endfor %}
    </div>

    {% if user.is_authenticated %}
        {% include "cms/update_subscriptions_modal.html" %}
    {% endif %}

    <script type="text/javascript" src="{% static 'cms/javascript/sort_by_category.js' %}"></script>
    <script>
        function show_modal() {
            $('.ui.modal').modal('show');
        }
        function hide_modal() {
            $('.ui.modal').modal('hide');
        }
        $('.ui.dropdown').dropdown();
    </script>

{% endblock %}

cms/templates/cms/update_subscriptions_modal.html
<div class="ui modal">
    <div class="ui text container">
        <form class="ui form" method="POST" action="{% url 'update_subscription' pk=request.user.subscription.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="ui primary button">Save</button>
            <button type="reset" onclick="hide_modal()" class="ui button">Cancel</button>
        </form>
    </div>
    <p><br></p>
</div>